### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by cauan** [etianen/django-herokuapp#14]
$ herokuapp_startproject.py test
Traceback (most recent call last):
  File "/test/venv/bin/herokuapp_startproject.py", line 9, in <module>
    load_entry_point('django-herokuapp==0.9.17', 'console_scripts', 'herokuapp_startproject.py')()
  File "/test/venv/lib/python2.7/site-packages/herokuapp/bin/herokuapp_startproject.py", line 52, in main
    audit_returncode = subprocess.call(audit_args)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
# 

I fixed it editing file: 'bin/herokuapp_startproject.py'
audit_args = ["python", os.path.join(args.dest_dir, "manage.py"), "heroku_audit", "--fix"]

**Comment by utkarsh1148** [comment]
how to set the exec permissions before call "manage.py".Pls tell

**Comment by etianen** [comment]
On your computer, run `chmod +x ./manage.py` in the project directory.

**Comment by utkarsh1148** [comment]
I am using windows.....this command won't help

**Comment by etianen** [comment]
This comment describes a source code change that fixes the issue.

https://github.com/etianen/django-herokuapp/issues/14#issue-25931143

I'm afraid that I'm not really maintaining this project any more. I'd advise copying it and adapting it to suit your own needs, or using a different project.
