### ISSUE TITLE
Error running herokuapp_startproject.py

### ISSUE THREAD

**Issue by brad** [etianen/django-herokuapp#25]
Using version 0.9.18

``` shell
$ herokuapp_startproject.py pootle
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    load_env(__file__, "pootle")
  File "/home/brad/projects/pootle/venv/lib/python2.7/site-packages/herokuapp/env.py", line 12, in load_env
    heroku_config = heroku.config_get()
  File "/home/brad/projects/pootle/venv/lib/python2.7/site-packages/herokuapp/commands.py", line 99, in config_get
    return parse_shell(self("config", shell=True, _out=None))
  File "/home/brad/projects/pootle/venv/lib/python2.7/site-packages/herokuapp/commands.py", line 20, in parse_shell
    in lines.split()
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

I get the same error any time I run `./manage.py shell` thereafter.

**Comment by 7wonders** [comment]
I think this needs reopening. I get this on a new project using 0.9.19 master

**Comment by etianen** [comment]
Could you paste the output of running `heroku config —shell` in your terminal, in the same folder as you were running herokuapp commands?

You’ll probably need to sanitise the output of any sensitive data.

**Comment by jensfinnas** [comment]
Same issue here. I get it with any `python manage.py` command.

`heroku config` gives me:

```
AWS_ACCESS_KEY_ID:           s3cret
AWS_SECRET_ACCESS_KEY:       s3cret
AWS_STORAGE_BUCKET_NAME:     my_app
DATABASE_URL:                postgres://s3cret
HEROKU_POSTGRESQL_MAUVE_URL: postgres://s3cret
PYTHONHASHSEED:              s3cret
SECRET_KEY:                  s3cret
SENDGRID_PASSWORD:           s3cret
SENDGRID_USERNAME:           s3cret
```

**Comment by etianen** [comment]
What does `heroku config —shell` give you. Seeing the full command output is rather important here.
