### ISSUE TITLE
HerokuCommandError

### ISSUE THREAD

**Issue by skhaz** [etianen/django-herokuapp#37]
Hi,

I got this error while running `erokuapp_startproject.py myawesomeapp` (from pip install)

``` shell
Create app? (y/n) > y
HerokuCommandError:

  RAN: '/usr/local/bin/heroku auth:token --app=myawesomeapp'

  STDOUT:


  STDERR:
```

If I install from master branch

``` shell
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    load_env(__file__, "myawesomeapp")
  File "/Users/Skhaz/.virtualenvs/herokuapp/lib/python2.7/site-packages/django_herokuapp-0.9.20-py2.7.egg/herokuapp/env.py", line 12, in load_env
    heroku_config = heroku.config_get()
  File "/Users/Skhaz/.virtualenvs/herokuapp/lib/python2.7/site-packages/django_herokuapp-0.9.20-py2.7.egg/herokuapp/commands.py", line 107, in config_get
    return parse_shell(self("config", shell=True, _out=None))
  File "/Users/Skhaz/.virtualenvs/herokuapp/lib/python2.7/site-packages/django_herokuapp-0.9.20-py2.7.egg/herokuapp/commands.py", line 92, in __call__
    raise HerokuCommandError(str(ex))
```

Do you have any clue?

**Comment by etianen** [comment]
It looks like your traceback from the master branch didn't include the
actual message from the HerokuCommandError

Could you include the full traceback and exception message?

**Comment by apotapov** [comment]
Got a similar issue:
```
$ herokuapp_startproject.py scaffold
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    load_env(__file__, "scaffold")
  File "/Users/user/work/scaffold/venv/lib/python2.7/site-packages/herokuapp/env.py", line 10, in load_env
    cwd = os.path.dirname(entrypoint),
  File "/Users/user/work/scaffold/venv/lib/python2.7/site-packages/herokuapp/commands.py", line 75, in __init__
    self("auth:token", _force_live_run=True, _in=None, _tty_in=True, _out=auth_token_interact, _out_bufsize=0).wait()
  File "/Users/user/work/scaffold/venv/lib/python2.7/site-packages/herokuapp/commands.py", line 91, in __call__
    raise HerokuCommandError(str(ex))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25b8' in position 86: ordinal not in range(128)
```

**Comment by etianen** [comment]
This was an easy fix, so I've just updated the master branch.

In general, this project hasn't really had any love for years. The README is still a pretty good setup guide, but the python code may be showing it's age.
