### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by pbowditch** [etianen/django-herokuapp#39]
I receive the following error on Windows running:

C:>pip install django-herokuapp
Collecting django-herokuapp
  Using cached django-herokuapp-0.9.20.tar.gz
Collecting django>=1.7 (from django-herokuapp)
  Using cached Django-1.9.7-py2.py3-none-any.whl
Collecting pytz (from django-herokuapp)
  Using cached pytz-2016.4-py2.py3-none-any.whl
Collecting waitress (from django-herokuapp)
  Using cached waitress-0.9.0-py2.py3-none-any.whl
Collecting dj-database-url (from django-herokuapp)
  Using cached dj-database-url-0.4.1.tar.gz
Collecting psycopg2 (from django-herokuapp)
  Using cached psycopg2-2.6.1-cp27-none-win32.whl
Collecting django-require-s3 (from django-herokuapp)
  Using cached django-require-s3-1.0.0.tar.gz
Collecting boto (from django-herokuapp)
  Using cached boto-2.40.0-py2.py3-none-any.whl
Collecting sh (from django-herokuapp)
  Using cached sh-1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\auser\appdata\local\temp\pip-build-daqnap\sh\setup.py", line 4, in <module>
        import sh
      File "sh.py", line 37, in <module>
        support." % **version**)
    ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in c:\users\auser\appdata\local\temp\pip-build-daqnap\sh\

To minimise dependencies on external modules (espcialle non windows compatible ones) could we not just use the subprocess module?  The code only appears to wrap the pip freeze and heroku commands at a very high level.

**Comment by etianen** [comment]
I'd definitely take a pull request to drop the dependency on sh by replacing it with a simple wrapper around subprocess.
